security:
    # Configuration des encodeurs de mots de passe
    password_hashers:
        App\Entity\Users:
            algorithm: bcrypt

    # Configuration du provider (qui utilise l'entité User)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email  # Utilise l'email comme identifiant unique

    # Configuration des firewalls pour la sécurité des pages
    firewalls:
        # Firewall principal avec la gestion de la connexion via un formulaire
        dev:
            pattern: ^/(_(profiler|wdt))
            security: false
        main:
            security: true
            lazy: true
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _email # Correspond au champ name="_username"
                enable_csrf: false 
                default_target_path: app_users  # Page après connexion réussie

            # Déconnexion et invalidation de session
            logout:
                path: /logout  # Symfony gère cette route automatiquement
                target: /login # Redirection après déconnexion
                invalidate_session: true  # Invalider la session après déconnexion
            # custom_authenticator:
            #     - App\Security\UsersAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true  # Toujours activer l'option "se souvenir de moi"

    # Définition des accès contrôlés (qui peut accéder à quelles pages)
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/users, roles: ROLE_USER }